services:

  meson:
    image: meson
    container_name: meson
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/work
    working_dir: /work
    tty: true
    command: /bin/bash
